

version: '3.0'

services:
  # Redis sentinel
  redis-master:
    volumes:
      - redis-sentinel-data-master:/bitnami/redis/data
  redis-slave:
    volumes:
      - redis-sentinel-data-slave:/bitnami/redis/data
  redis-sentinel:
    volumes:
      - redis-sentinel-data-sentinel:/bitnami/redis/data

volumes:
  redis-sentinel-data-master:
    external:
      name: ${REDIS_SENTINEL_DATA_VOLUME_MASTER}
  redis-sentinel-data-slave:
    external:
      name: ${REDIS_SENTINEL_DATA_VOLUME_SLAVE}
  redis-sentinel-data-sentinel:
    external:
      name: ${REDIS_SENTINEL_DATA_VOLUME_SENTINEL}
