

version: '3.0'

services:
  # Redis sentinel
  redis-master:
    image: 'bitnami/redis:7.0'
    volumes:
      - ./tb-node/redis-sentinel-data-master:/bitnami/redis/data
    environment:
      - 'REDIS_REPLICATION_MODE=master'
      - 'REDIS_PASSWORD=thingsboard'

  redis-slave:
    image: 'bitnami/redis:7.0'
    volumes:
      - ./tb-node/redis-sentinel-data-slave:/bitnami/redis/data
    environment:
      - 'REDIS_REPLICATION_MODE=slave'
      - 'REDIS_MASTER_HOST=redis-master'
      - 'REDIS_MASTER_PASSWORD=thingsboard'
      - 'REDIS_PASSWORD=thingsboard'
    depends_on:
      - redis-master

  redis-sentinel:
    image: 'bitnami/redis-sentinel:7.0'
    volumes:
      - ./tb-node/redis-sentinel-data-sentinel:/bitnami/redis/data
    environment:
      - 'REDIS_MASTER_HOST=redis-master'
      - 'REDIS_MASTER_SET=mymaster'
      - 'REDIS_SENTINEL_PASSWORD=sentinel'
      - 'REDIS_MASTER_PASSWORD=thingsboard'
    depends_on:
      - redis-master
      - redis-slave

  # ThingsBoard setup to use redis-sentinel
  tb-core1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-core2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-rule-engine1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-rule-engine2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-mqtt-transport1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-mqtt-transport2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-http-transport1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-http-transport2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-coap-transport:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-lwm2m-transport:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-snmp-transport:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-vc-executor1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-vc-executor2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
